version: "3.4"

services:
  app:
    build: .
    volumes:
    - ./app.py:/usr/src/app/app.py
    environment:
    - UPSTREAM_URL=https://httpbin.org/
    restart: always
    ports:
    - 127.0.0.1:8080:8080
  nginx:
    image: nginxinc/nginx-unprivileged:1.21.4
    environment:
    - LIMIT_RATE=1r/s
    - UPSTREAM_URL=http://httpbin.org
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
