version: "3.4"

services:
  app:
    build: .
    volumes:
    - ./app.py:/usr/src/app/app.py
    environment:
    - UPSTREAM_URL=https://httpbin.org/
    - LIMIT_RATE=1/second
    restart: always
    ports:
    - 127.0.0.1:8080:8080
